version: '3'

services:
  app:
    image: ghcr.io/naimeds10/bussenbot:latest
    restart: unless-stopped
    env_file: .env
    environment:
      - NODE_ENV=production
    volumes:
      - /opt/app/node_modules
