name: Cleanup Registry

on:
    schedule:
        - cron: '0 0 * * 1' # https://crontab.guru/#0_0_*_*_1
    workflow_dispatch:

env:
    IMAGE_NAMES: discordbussenbot/bussenbot

jobs:
    cleanup:
        name: Cleanup
        runs-on: ubuntu-latest
        steps:
            - name: Delete old versions
              uses: snok/container-retention-policy@v2
              with:
                  image-names: ${{ env.IMAGE_NAMES }}
                  cut-off: 2 days ago UTC
                  account-type: personal
                  skip-tags: latest
                  token: ${{ secrets.PAT }}
