name: Continuous Delivery

on:
  workflow_dispatch:

concurrency:
  group: cd-${{ github.ref_name }}

env:
  PROJECT_NAME: bussenbot
  SENTRY_ORG: geesee
  APP_ID: 154315

jobs:
  branch_check:
    name: Branch Check
    runs-on: ubuntu-latest
    steps:
      - name: Validate branch
        run: |
          if [ $GITHUB_REF_NAME != 'master' ]; then
            echo 'This workflow can only be run on the master branch.'
            exit 1
          fi

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: branch_check
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Start deployment
        uses: bobheadxi/deployments@v0.4.3
        id: start_deployment
        with:
          step: start
          token: ${{ secrets.GITHUB_TOKEN }}
          env: production

      - name: Deploy
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.SSH_HOST }}
          username: github-actions
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          envs: PROJECT_NAME
          script: |
            cd /opt/docker/$PROJECT_NAME/production
            docker-compose pull
            docker-compose up -d

      - name: Finalize Sentry release
        uses: getsentry/action-release@v1
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_PROJECT: ${{ env.PROJECT_NAME }}
        with:
          environment: production
          set_commits: skip

      - name: Finish deployment
        uses: bobheadxi/deployments@v0.4.3
        if: steps.start_deployment.conclusion == 'success' && always()
        with:
          step: finish
          token: ${{ secrets.GITHUB_TOKEN }}
          status: ${{ job.status }}
          deployment_id: ${{ steps.start_deployment.outputs.deployment_id }}

  update_check_run:
    name: Update Check Run
    runs-on: ubuntu-latest
    needs: [branch_check, deploy]
    if: github.ref_name == 'master' && always()
    steps:
      - name: Get conclusion
        id: get_conclusion
        env:
          RESULTS: ${{ join(needs.*.result, ' ') }}
        run: |
          for RESULT in $RESULTS; do
            if [ $RESULT = 'cancelled' ] || [ $RESULT = 'failure' ]; then
              echo '::set-output name=conclusion::'$RESULT
              exit
            fi
          done
          echo '::set-output name=conclusion::success'

      - name: Update Continuous Delivery check run
        uses: guidojw/actions/update-check-run@v1
        with:
          app_id: ${{ env.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}
          sha: ${{ needs.merge.outputs.sha }}
          name: Continuous Delivery
          conclusion: ${{ steps.get_conclusion.outputs.conclusion }}
          details_url: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
